FROM nginx
COPY ./chapter07/dist/index.html /usr/share/nginx/html/index.html
COPY ./chapter07/dist/assets /usr/share/nginx/html/assets
COPY ./chapter07/dist/css /usr/share/nginx/html/css
COPY ./chapter07/dist/js /usr/share/nginx/html/js
